service: frontend
runtime: nodejs20

instance_class: F2

env_variables:
  VITE_FIREBASE_API_KEY: "AIzaSyApdce8TMmnIUkamZiRmlNM409NJRZzs24"
  VITE_FIREBASE_AUTH_DOMAIN: "kyrotics.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID: "kyrotics"
  VITE_FIREBASE_STORAGE_BUCKET: "kyrotics.appspot.com"
  VITE_FIREBASE_MESSAGING_SENDER_ID: "576941623096"
  VITE_FIREBASE_APP_ID: "1:576941623096:web:2452601bf4299a66c923cd"
  VITE_FIREBASE_MEASUREMENT_ID: "G-D1VEFYTFYR"
  VITE_SERVER_URL: "https://bhasantar-ui-and-llm.as.r.appspot.com"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

handlers:
  # Serve static assets with correct MIME types
  - url: /static
    static_dir: dist/static

  - url: /(.*\.js)
    static_files: dist/\1
    upload: dist/.*\.js

  - url: /(.*\.css)
    static_files: dist/\1
    upload: dist/.*\.css

  - url: /(.*\.(ico|png|svg|jpg))
    static_files: dist/\1
    upload: dist/.*\.(ico|png|svg|jpg)

  # Catch-all handler to serve index.html for other routes
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html

